on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI command test
      uses: azure/CLI@v1
      with:
        azcliversion: 2.4.0
        inlineScript: |
          az keyvault show -n bim-kv5
